INIT_TABLE_FILES =  '''
	CREATE TABLE FILES (
		ID INTEGER PRIMARY KEY AUTOINCREMENT,
		TITLE varchar(255) NOT NULL,
		GENRE varchar(255),
		LOCATION varchar(255)
	);'''

INIT_TABLE_TAGS = '''
	CREATE TABLE TAGS (
		FILE_ID int NOT NULL,
		TAG varchar(255),
		PRIMARY KEY (FILE_ID, TAG),
		FOREIGN KEY (FILE_ID) REFERENCES FILES(ID)
	);
	'''

INIT_TABLE_AUTHORED = '''
	CREATE TABLE AUTHORED (
		FILE_ID int NOT NULL,
		AUTHOR varchar(255),
		PRIMARY KEY (FILE_ID, AUTHOR),
		FOREIGN KEY (FILE_ID) REFERENCES FILES(ID)
	);
	'''

TABLE_FILES = 'FILES'
TABLE_TAGS = 'TAGS'
TABLE_AUTHORED = 'AUTHORED'

ATTR_ID = 'ID'
ATTR_FILE_ID = 'FILE_ID'
ATTR_TITLE = 'TITLE'
ATTR_GENRE = 'GENRE'
ATTR_TAG = 'TAG'
ATTR_AUTHOR = 'AUTHOR'

INSERT_TAG = 'INSERT INTO TAGS (FILE_ID, TAG) VALUES (?, ?)'
INSERT_FILE = 'INSERT INTO FILES (TITLE, GENRE, LOCATION) VALUES (?, ?, ?)'
INSERT_AUTHORED = 'INSERT INTO AUTHORED (FILE_ID, AUTHOR) VALUES (?, ?)'

QUERY_FILE_BY_ID = 'SELECT * FROM FILES WHERE ID=?'
QUERY_FILE_BY_TITLE = 'SELECT * FROM FILES WHERE TITLE=?'
QUERY_FILE_BY_GENRE = 'SELECT * FROM FILES WHERE GENRE=?'

QUERY_TEMPLATE_NO_CONDITION = 'SELECT {} FORM {}'
QUERY_TEMPLATE = 'SELECT {} FROM {} WHERE{}'
QUERY_CONDITION_EQUAL = ' {}=?'
QUERY_CONDITION_LIKE = ' {} LIKE ?'
AND = ' AND '
OR = ' OR '

EMPTY_SPACE = '{}'


# TODO: Create a query by tags
# TODO: Create a query by authors
